# Generated by Django 6.0.3 on 2026-03-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_category_note_delete_todo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
