# Generated by Django 6.0.3 on 2026-03-26 03:13

from django.db import migrations

DEFAULT_CATEGORIES = [
    {'name': 'Random Thoughts', 'color': '#EF9C66'},
    {'name': 'School', 'color': '#FCDC94'},
    {'name': 'Personal', 'color': '#78ABA8'},
]


def seed_categories(apps, schema_editor):
    Category = apps.get_model('todos', 'Category')
    for cat in DEFAULT_CATEGORIES:
        Category.objects.get_or_create(name=cat['name'], defaults={'color': cat['color']})


def remove_categories(apps, schema_editor):
    Category = apps.get_model('todos', 'Category')
    Category.objects.filter(name__in=[c['name'] for c in DEFAULT_CATEGORIES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_category_options_remove_category_user_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_categories, remove_categories),
    ]
